services:
  postgres:
    image: postgres:15
    container_name: moa_postgres_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moa_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
